### ISSUE TITLE
Show input and outputs from all actions

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-chrome-extension#1]
I was thinking, it would be nice to be able to see the inputs and outputs from all actions triggered by signals, not just the state changes.

What do you think of this?

**Comment by christianalfoni** [comment]
Hi!

I think this is a great idea! I am a little bit unsure where to display it though and in what way. Because each action may have an output, which is the input for the next action. But we also the "main signal input" which shows all inputs across the chain. So it is more a matter of where to put it in the debugger, than anything else.

Maybe it should just be a link? So you can click an "input"/"output" link on each action, and that will log out the data?

**Comment by saulshanabrook** [comment]
I said earlier "inputs and outputs" but now that I am thinking about it, really just the data that is passed between.

The simplest way it seems like would be to have an arrow between each action and you click on it and it shows the data being transferred between.

Before I was thinking maybe a graph interface would make sense (like [this](http://visjs.org/network_examples.html)or [this](http://js.cytoscape.org/) or [this](http://sigmajs.org/)) but that is probably overkill

**Comment by christianalfoni** [comment]
This is part of next release

**Comment by saulshanabrook** [comment]
@christianalfoni :+1:
